# -*- coding: utf-8 -*-
"""q2_library_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq2z_G1UqOExHoRXkzv0F5-hyFeQ91ao
"""

# q2_library_system

def add_book(catalog, book_id, title, author, year):
    catalog[book_id] = (title, author, year)


def borrow_book(catalog, borrowed_books, book_id):
    if book_id in catalog:
        if book_id not in borrowed_books:
            borrowed_books.append(book_id)
            print(f"Book {book_id} borrowed successfully.")
        else:
            print(f"Book {book_id} is already borrowed.")
    else:
        print("Book not found.")


def return_book(borrowed_books, book_id):
    if book_id in borrowed_books:
        borrowed_books.remove(book_id)
        print(f"Book {book_id} returned successfully.")
    else:
        print("Book was not borrowed.")


def register_member(members, member_id):
    members.add(member_id)   # Duplicates are ignored automatically


def show_available(catalog, borrowed_books):
    print("\nAvailable Books:")
    for book_id, details in catalog.items():
        if book_id not in borrowed_books:
            title, author, year = details
            print(f"{book_id}: {title} by {author} ({year})")


def main():
    catalog = {}
    borrowed_books = []
    members = set()

    # Add 4 books
    add_book(catalog, 101, "Python Basics", "John Smith", 2020)
    add_book(catalog, 102, "Data Structures", "Alice Brown", 2019)
    add_book(catalog, 103, "Machine Learning", "Tom Lee", 2021)
    add_book(catalog, 104, "Database Systems", "Sara Wilson", 2018)

    # Register members
    register_member(members, 1)
    register_member(members, 2)
    register_member(members, 3)
    register_member(members, 2)   # Duplicate ignored

    print("Registered Members:", members)

    # Borrow books
    borrow_book(catalog, borrowed_books, 101)
    borrow_book(catalog, borrowed_books, 103)

    # Return one book
    return_book(borrowed_books, 101)

    # Display available books
    show_available(catalog, borrowed_books)


if __name__ == "__main__":
    main()