# -*- coding: utf-8 -*-
"""q3_shopping_cart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq2z_G1UqOExHoRXkzv0F5-hyFeQ91ao
"""

# q3_shopping_cart

# -------------------------
# Part A - Spot the Bug
# -------------------------

def add_item(item, cart=[]):
    cart.append(item)
    return cart


print("Part A Output:")
print(add_item("apple"))
print(add_item("banana"))
print(add_item("milk", cart=["bread"]))
print(add_item("eggs"))

# Output:
# ['apple']
# ['apple', 'banana']
# ['bread', 'milk']
# ['apple', 'banana', 'eggs']
#
# Explanation:
# The default list (cart=[]) is created only once when the function is
# defined. Every call that doesn't provide a cart uses the same list.


# -------------------------
# Part B - Fix It
# -------------------------

def add_item_fixed(item, cart=None):
    if cart is None:
        cart = []
    cart.append(item)
    return cart


print("\nPart B Output:")
print(add_item_fixed("apple"))
print(add_item_fixed("banana"))
print(add_item_fixed("milk", ["bread"]))
print(add_item_fixed("eggs"))


# -------------------------
# Part C - Shopping Cart
# -------------------------

def create_cart(owner, discount=0):
    return {
        "owner": owner,
        "items": [],
        "discount": discount
    }


def add_to_cart(cart, name, price, qty=1):
    cart["items"].append({
        "name": name,
        "price": price,
        "qty": qty
    })


def update_price(price_tuple, new_price):
    try:
        # Tuples are immutable, so this raises TypeError
        price_tuple[1] = new_price
    except TypeError as e:
        print("\nTuple Error:", e)


def calculate_total(cart):
    total = 0

    for item in cart["items"]:
        total += item["price"] * item["qty"]

    total -= total * (cart["discount"] / 100)
    return total


# Create two separate carts
cart1 = create_cart("Alice", 10)
cart2 = create_cart("Bob")

# Add items to first cart
add_to_cart(cart1, "Laptop", 50000, 1)
add_to_cart(cart1, "Mouse", 1000, 2)

# Add items to second cart
add_to_cart(cart2, "Notebook", 50, 5)
add_to_cart(cart2, "Pen", 10, 10)

print("\nCustomer 1 Cart:")
print(cart1)
print("Total:", calculate_total(cart1))

print("\nCustomer 2 Cart:")
print(cart2)
print("Total:", calculate_total(cart2))

# Demonstrate tuple immutability
price = ("Laptop", 50000)
update_price(price, 55000)


# -------------------------
# Discussion Points
# -------------------------

# 1. Why is discount=0 safe but cart=[] dangerous?
#    discount=0 is immutable, so every call gets the same value safely.
#    cart=[] is mutable, so all calls without an argument share the same list.

# 2. What is the difference between rebinding and mutating?
#    Rebinding means assigning a variable to a new object.
#    Mutating means changing the contents of the existing object.

# 3. Which of these are mutable?
#    list  -> Mutable
#    tuple -> Immutable
#    dict  -> Mutable
#    set   -> Mutable
#    str   -> Immutable
#    int   -> Immutable

# 4. When you pass a list into a function and modify it,
#    do changes reflect outside? Why?
#    Yes. A list is mutable, and the function receives a reference
#    to the same list object. Mutating it inside the function changes
#    the original list.